---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.secrets-manager-transit.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.secrets-manager-transit.host | quote }}
