---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.secretsManagerTransit.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.secretsManagerTransit.host | quote }}
