{{- if .Values.secretsManagerTransit.tokenSecret.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: transit-unseal-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  VAULT_TOKEN: {{ .Values.secretsManagerTransit.tokenSecret.value | quote }}
{{- end }}
