#!/usr/bin/env bash

set -e

echo "Deleting transit token secret from the cluster..."

# We use a dummy value for the token here just to satisfy the Helm template rendering.
# kubectl delete only uses the resource type, name, and namespace from the generated YAML.
helm template transit-secret ./helm \
    -n secrets-manager \
    -s templates/transit-secret.yaml \
    --set secretsManagerTransit.tokenSecret.enable=true \
    --set-string secretsManagerTransit.tokenSecret.value="dummy-value-for-deletion" \
    | kubectl delete --ignore-not-found -f -

echo "Transit token secret successfully deleted."
